### ISSUE TITLE
Look into StandardJS

### ISSUE THREAD

**Issue by alexewerlof** [schibsted/eslint-config-spt#47]
Messaging team is using [it](
http://standardjs.com/). Do a bit of research to see how it compares.

> we don't override it. we just npm install it. you can override. but they strongly discourage it. as they’re trying to build a community driven coding standard. if everybody overrides it a bit, it won’t be that standard anymore

---

> will only run the linters on staged files (pre-commit hook) https://www.npmjs.com/package/lint-staged

**Update: their config is here: https://github.com/feross/eslint-config-standard**

**Comment by SimenB** [comment]
I'd at least use `semistandard`.
But my problem with `standard` is it moves very slowly in order to not break. It doesn't for instance yell at you for using `var` instead of `let`/`const`. See its rules here: https://github.com/feross/eslint-config-standard/blob/master/eslintrc.json

There's also no React rules etc

If the standard toolchain could be used with airbnb's config, we'd be golden IMO 😄

**Comment by nosilleg** [comment]
Addressed in https://github.com/schibsted/eslint-config-schibsted/pull/74 by going with AirBnB instead. Suggest closing this issue as wontfix.

**Comment by nosilleg** [comment]
As per my last message, closing this as we've gone with AirBnB.
