### ISSUE TITLE
Idea: base it on airbnb

### ISSUE THREAD

**Issue by marek-nogiec** [schibsted/eslint-config-spt#51]
Easier to maintain and we can override what we need and we need.
If we want we can freeze for a while on a certain version of the base config.
Could convince people who want the latest features from airbnb to use it.

**Comment by alexewerlof** [comment]
This is an interesting idea and I'll just paste a bit of discussion from Slack into this:

Pros:

* lower development cost (if we go with the gist approach)
* easier adoption because airbnb is quite popular and people’s muscle memory has already learned it.
* You get all updates to AirBnB, which is a very active project, a lot easier

Cons:

* This will introduce a dependency to the `eslint-config-schibsted` which is currently usable standalone.
* Using Airbnb as a base is a confession to uselessness of this initiative because at best we end up adding an opinionated override ruleset on top of that which I suppose everyone will be doing differently anyway.
* If the repo purpose is changed to a  “consistent” override on top of Airbnb, then we better write a gist and share it. Not sure if it justifies all the trouble with setting up travis, publishing to npm, etc.
* Branding. We’re not Airbnb. I mean I know some ppl prefer airbnb and respect that but if someone wants to use `-schibsted` as a way to adopt the consesus of brainpower within the company, I suppose we can handle it independently. We might end up with something quite similar to Airbnb, but we’ll have control over it.
* This still won't solve one of the issues with have with Airbnb: the fact that we'll be dependent to their design choices and preferences (which don't necessarily comply with the consensus within Schibsted)

**Comment by marek-nogiec** [comment]
to elaborate a bit why updates from community are so important - there is a lot of people who keep an eye on not only good practices but also stuff that can help with security and accessibility just by adhering to simple rules the add there, maybe it's a bit more work sometimes but imo it's worth it, and I don't think we have the resources (maybe I'm wrong here) to do the same and be up to speed with everything that's going on

I don't necessarily agree with the second con. If we need some overrides that are justified org-wide then it makes sense, then still people will have the same config. The point is to discourage people from overriding coz no matter if it is or isn't based on an external config this could still happen.

As for setting up travis etc - we do it once and then just publish an update, right? People won't use a gist coz it doesn't work as automatically ;)

Branding - do people really care as much? We use a lot of tools from a lot of companies, this is just another one that they did well and we have as much control as we want via versioning & overrides.

As for the last point - we will never reach that consensus ;) And it also doesn't matter whether it's based on airbnb or it's on our base.

**Comment by alexewerlof** [comment]
>  and I don't think we have the resources (maybe I'm wrong here) to do the same and be up to speed with everything that's going on

That's a fair point. Previously `eslint-config-spt` was suffering from the same issue. However, if being up to date with the latest rules is a priority, any of the popular ones (airbnb, google, standard, xo, etc.) should be better than `eslint-config-schibsted` at the moment.

There is enough brain power in Schibsted to maintain such a config on our own, but at the moment we don't have enough traction to make a promise there. Many people are using other configs and in order to focus their energy on this repo, we first must break out of that catch 22 loop (it's not popular because it's not perfect but it'll not be perfect unless it's used in a good number of projects). To break that loop, we want to make it as easy as possible to transition to this config.ie. Airbnb compatibility :)

**Comment by trygve-lie** [comment]
Just a minor comment on the community part. If one look at the history of AirBnB Config its really just two AirBnB employees making most of the calls. Community can comment and make PR but its really what those two decide to land which gets in. It is a company config for AirBnB.

That the repo has a lot of stars on github does not equal great community interaction or control. I would take the phrase community with a large grain of salt.

**Comment by ivarconr** [comment]
One could also argue to make this repo private or move it to our GitHub Enterprise. We do this for our self, and to support our own projects for a long time. 

Is there any real value for others that we open source yet another lint config?

**Comment by alexewerlof** [comment]
I think it's more of a PR (as in public relations) thing. 
Though given how much time I spent on this and all the feedback we got and will get, I for one week use it in my personal projects.

**Comment by alexewerlof** [comment]
> * will use.
Damn auto correct and github for not allowing edits on their mobile site.

**Comment by ivarconr** [comment]
Actually it makes sense to keep it open if it's used in other open source projects from the company.

**Comment by alexewerlof** [comment]
Oh you're right. I totally forgot SPiD SDK which is open source.

**Comment by SimenB** [comment]
> That the repo has a lot of stars on github does not equal great community interaction or control. I would take the phrase community with a large grain of salt.

Community involvement in maintaining it I don't really care about and I don't really see how that's relevant. That said they currently have 293 contributors, so I don't think it's a fair statement either.
But what _is_ interesting is that the community uses it. Can you show me an example of a project allowing "anyone" to make a lot of changes actually getting somewhere and not continually bikeshed over every single, little thing?
The fact that the preset has almost a million downloads a month speaks about a very well accepted config, and I think sticking close to it would help us.

And while there are times they will make decisions on what goes in which goes against what we might want, most of the point of this config to me is that we're able to overwrite it, but still hopefully use a shared style across Schibsted

Whether er not we should copy airbnb rules over and watch for changes or depend directly upon it, I have no opinion 😄 Either works for me. But the style itself IMO should be a thin layer upon Airbnb style, as it is as close to an accepted standard that we can get, I think.

**Comment by voldern** [comment]
:+1: to @userpixel for spearheading the reboot of the initiative an being open to discussions. 

Another pro with going for AirBnB is also that we can prevent a lot of bike shedding/drawn out discussions internally whenever we introduce a new change.

Our previous project we used the [VG Eslint configuration](https://www.npmjs.com/package/eslint-config-vgno) (that ended up going stale after a while). When we started our new project we decided to just "swallow the bitter pill" and go for AirBnB even though there were things like 4 vs 2 spaces and dangling commas that we weren't used to, just to have an actively maintained standard to follow and to prevent the inevitable coding style discussions.

> Using Airbnb as a base is a confession to uselessness of this initiative because at best we end up adding an opinionated override ruleset on top of that which I suppose everyone will be doing differently anyway.

I don't think that is necessarily the case. There are things that aren't (currently) covered by AirBnB that we could add out of necessity as an extension on top if several teams does this already. This could be rules for [promises](https://github.com/xjamundx/eslint-plugin-promise) and [flowtypes](https://github.com/gajus/eslint-plugin-flowtype) for example.

See spt-mediaplatform/curate-eslint for our AirBnB extension with those two plugins.

One other pro that I think is worth mentioning is that its a possibility that people already working in, and joining the company in the future, have been exposed to the AirBnB standard before so the transition for them will have less friction. Though it could be argued that switching coding standards shouldn't be too hard with a capable editor.

To be blunt, from my perspective not going with an active community standard but creating our own from scratch feels like Not Invented Here.

(AirBnB is an example here, I haven't looked into XO https://github.com/schibsted/eslint-config-schibsted/issues/53)

**Comment by SimenB** [comment]
FWIW, if it came down to a vote, I'd prefer directly extending Airbnb instead of copying over its rules, in order to have a maintained base.

The only real drawback I see is the amount of peer dependencies, but I don't think it's a huge issue.

**Comment by alexewerlof** [comment]
Well for what its worth, @voldern is one of the developers I highly respect at Schibsted and @SimenB is one of the main contributors to the project.
If there's consensus that it's the way to go, I'm ok with it too.
That being said, I've been working almost every evening on the changes I had in mind and I tend to continue that project so I'll not have too much time to contribute to the airbnb-based solution. Maybe someone else can step up and take over if that's the way to go.

**Comment by alexewerlof** [comment]
So if no one else is working on it, I can put a basic airbnb solution for v 4 and then you guys can discuss overrides on top of it.

**Comment by alexewerlof** [comment]
still haven't had time to do this. A proper execution will keep the current config file names for backwards compatibility while delegating to airbnb rules when possible (and add the missing ones).
As I said on Slack I'm not fund of the solution, so if anyone else is interested maybe you can make a PR?

**Comment by nosilleg** [comment]
Addressed in https://github.com/schibsted/eslint-config-schibsted/pull/74 by extending AirBnB.

**Comment by nosilleg** [comment]
Closing as fixed in version 6.
